blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
        path('', views.index, name='index'),
        path('detail/<int:blog_id>/', views.detail, name='detail'),
        path('add_form', views.add_form, name='add_form'),
]

gohannblog/urls.py
#from django.contrib import admin
#from django.urls import path, include

#urlpatterns = [
#    path('admin/', admin.site.urls),
#    path("", include("blog.urls")),
#    path('album/', include('album.urls')),
#]

from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse_lazy

from django.utils import timezone
from django.contrib.auth.models import User

class Blog(models.Model):
    title = models.CharField('タイトル', max_length=50)
    text = models.TextField('テキスト')
    created_at = models.DateField('作成日', auto_now_add=True)
    updated_at = models.DateField('更新日', auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'ブログ'
        verbose_name_plural = 'ブログ'

blog/forms.py
from django import forms
from .models import Blog

from django_summernote.widgets import SummernoteWidget


class BlogForm(forms.ModelForm):

    class Meta:
        model = Blog
        fields = ('title', 'text')
        widgets = {
                'text': SummernoteWidget(),
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Blog
from .forms import BlogForm
from django.http import JsonResponse

def index(request):
    blog = Blog.objects.order_by('-id')
    return render(request, 'blog/index.html', {'blog': blog })




def detail(request, blog_id):
    blog_text = get_object_or_404(Blog, id=blog_id)
    return render(request, 'blog/detail.html', {'blog_text': blog_text })

def add_form(request):

    if request.method == "POST":
        form = BlogForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('blog:index')

    else:
        form = BlogForm

    return render(request, 'blog/form.html', {'form': form })

def good(request, pk):
    """いいねボタンをクリック."""
    post = get_object_or_404(Blog, pk=pk)

    if request.method == 'POST':
        post.good += 1
        post.save()

    return redirect('board:board')

blog/templates/blog/base.html
<!doctype html>
<html>
    <head>

        <title>お料理日記</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="/">れいやのお料理日記</a>
        </nav>
        <div class="container mt-4"></div>
        {% block content %}
        <form action="{% url 'board:good' post.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" name="good" value="いいね" id="test">（{{ post.good }} いいね）
        </form>
        {% endblock %}
    </body>
</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block content %}

    <h1>{{ blog_text.title }}</h1>
    <p>{{ blog_text.updated_at }}</p>
    {{ blog_text.text | safe }}<hr />
    <br>

    <a href="{% url 'blog:index' %}">トップページに戻る</a>

{% endblock %}

blog/templates/blog/form.html
{% extends 'blog/base.html' %}

{% block content %}

    <a href="{% url 'blog:index' %}">トップページに戻る</a>

    <form action="{% url 'blog:add_form' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">投稿</button>
    </form>

{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}

    <h1>一覧</h1>
    <br>

    <a href="{% url 'blog:add_form' %}">追加</a>

    {% for blog in blog %}
        <ul>
            <li>
                {{ blog.created_at }}
                {{ blog.title }}
                <a href="{% url 'blog:detail' blog_id=blog.id %}">詳細</a>
            </li>
        </ul>
    {% endfor %}

{% endblock %}